 name: 'Release Local'
 on:
   workflow_dispatch:
   push:
     branches:
       - main
   pull_request:

 # make sure to have only one job from the same "trigger" at any time
 concurrency:
   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
   cancel-in-progress: true

 jobs:
   ios-xcframework:
     runs-on: 'macos-latest'
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: '17'
           cache: 'gradle'
       - run: ./gradlew podPublishXCFramework
       - uses: actions/upload-artifact@v4
         with:
             name: SPMobileCore.xcframework
             path: ./core/build/cocoapods/publish/release/SPMobileCore.xcframework
   android-aar:
     runs-on: 'macos-latest'
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: '17'
           cache: 'gradle'
       - run: ./gradlew :core:assembleRelease
       - uses: actions/upload-artifact@v4
         with:
             name: mobile-core.aar
             path: ./core/build/outputs/aar/core-release.aar
