name: 'Test'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# make sure to have only one job from the same "trigger" at any time
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ios:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew :core:iosSimulatorArm64Test
  android:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew :core:testDebugUnitTest
