name: 'Test'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# make sure to have only one job from the same "trigger" at any time
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ios:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          add-job-summary: 'on-failure'
      - name: Cache Kotlin Konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}-ios
      - run: ./gradlew :core:iosSimulatorArm64Test
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: android-test-reports
         path: '**/build/reports/tests'
  android:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'on-failure'
      - name: Cache Kotlin Konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}-android
      - run: ./gradlew :core:testDebugUnitTest
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-reports
          path: '**/build/reports/tests'
